// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const _url = import.meta.env.VITE_SUPABASE_URL;
const _key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const isTest = import.meta.env.MODE === 'test';
const SUPABASE_URL = _url || (isTest ? 'https://stub.supabase.co' : '');
const SUPABASE_PUBLISHABLE_KEY = _key || (isTest ? 'stub-anon-key' : '');

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing required environment variables: VITE_SUPABASE_URL and ' +
    'VITE_SUPABASE_PUBLISHABLE_KEY must be set in your .env file.'
  );
}

const safeFetch = async (input: RequestInfo, init?: RequestInit): Promise<Response> => {
  const controller = new AbortController();
  const timeoutMs = 10000;
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const signal = init?.signal
      ? AbortSignal.any([init.signal, controller.signal])
      : controller.signal;
    const res = await fetch(input, { ...(init ?? {}), signal });
    return res;
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    const isAbortError =
      (err instanceof DOMException && err.name === 'AbortError') ||
      /aborted/i.test(message);

    if (isAbortError) {
      throw err;
    }

    console.error('[supabase][fetch] network error:', message);
    throw new Error(`NetworkError: ${message}`);
  } finally {
    clearTimeout(timeout);
  }
};

type PersistedSupabaseSession = {
  expires_at?: number;
  refresh_token?: string | null;
};

const isBrowser = typeof window !== 'undefined';

// SEC-006: Proactively purge legacy JWT auth keys from localStorage to prevent XSS exfiltration
if (isBrowser) {
  try {
    const keysToRemove: string[] = [];
    for (let i = 0; i < window.localStorage.length; i++) {
      const k = window.localStorage.key(i);
      if (k && (k.startsWith('sb-') || k.includes('auth-token') || k.includes('supabase.auth'))) {
        keysToRemove.push(k);
      }
    }
    keysToRemove.forEach(k => window.localStorage.removeItem(k));
  } catch {
    /* ignore storage error */
  }
}

export const safeStorage: Storage = {
  get length() {
    return isBrowser ? window.sessionStorage.length : 0;
  },
  clear() {
    if (isBrowser) {
      window.sessionStorage.clear();
      try {
        const keysToRemove: string[] = [];
        for (let i = 0; i < window.localStorage.length; i++) {
          const k = window.localStorage.key(i);
          if (k && (k.startsWith('sb-') || k.includes('auth-token') || k.includes('supabase.auth'))) {
            keysToRemove.push(k);
          }
        }
        keysToRemove.forEach(k => window.localStorage.removeItem(k));
      } catch {
        /* ignore */
      }
    }
  },
  getItem(key: string) {
    if (!isBrowser) return null;

    // Ensure legacy token in localStorage is purged if accessed
    try {
      if (window.localStorage.getItem(key)) {
        window.localStorage.removeItem(key);
      }
    } catch {
      /* ignore */
    }

    const raw = window.sessionStorage.getItem(key);
    if (!raw) return null;

    try {
      const parsed = JSON.parse(raw) as PersistedSupabaseSession;
      const nowInSeconds = Math.floor(Date.now() / 1000);
      const isExpired = typeof parsed.expires_at === 'number' && parsed.expires_at <= nowInSeconds;
      const hasRefreshToken = typeof parsed.refresh_token === 'string' && parsed.refresh_token.length > 0;

      if (isExpired || !hasRefreshToken) {
        window.sessionStorage.removeItem(key);
        return null;
      }
    } catch {
      window.sessionStorage.removeItem(key);
      return null;
    }

    return raw;
  },
  key(index: number) {
    return isBrowser ? window.sessionStorage.key(index) : null;
  },
  removeItem(key: string) {
    if (isBrowser) {
      window.sessionStorage.removeItem(key);
      try {
        window.localStorage.removeItem(key);
      } catch {
        /* ignore */
      }
    }
  },
  setItem(key: string, value: string) {
    if (isBrowser) {
      // SEC-006: Ensure token is NEVER saved to persistent localStorage
      try {
        window.localStorage.removeItem(key);
      } catch {
        /* ignore */
      }
      window.sessionStorage.setItem(key, value);
    }
  },
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: safeFetch,
  },
});
